class ProviderError(Exception): ...
class AuthError(ProviderError): ...
class RateLimitError(ProviderError): ...
class TimeoutError(ProviderError): ...
class ContextOverflowError(ProviderError): ...
class NetworkError(ProviderError): ...
class ToolFormatError(ProviderError): ...
